#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct SSBO
{
    int2 sizes;
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(1u);

kernel void main0(device SSBO& ssbo [[buffer(0)]], texture2d<float> uSamp [[texture(0)]], texture2d<float, access::read_write> uSampo [[texture(1)]])
{
    ssbo.sizes = int2(int(uSamp.get_width() * uSamp.get_height()), int(uSampo.get_width() * uSampo.get_height()));
}

